{
 "title": "Mikrotik snmp prometheus",
 "description": "Mikrotik snmp monitoring (prometheus)",
 "tags": [
  "prometheus",
  "Mikrotik",
  "snmp",
  "snmp v3",
  "snmp_exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifHCInOctets,  instance)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(ifHighSpeed{instance='$instance'},ifIndex)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   },
   {
    "name": "desc",
    "query": {
     "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
    }
   },
   {
    "name": "queuesimple_name",
    "query": {
     "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_name",
    "query": {
     "query": "query_result((mtxrQueueTreePackets * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_parent",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_flow",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeName) group_left(mtxrQueueTreeIndex) mtxrQueueTreeIndex{instance='$instance',}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RouterOS date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(hrSystemDate{instance='$instance'})"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlTemperature{instance='$instance'}/10"
    }
   ]
  },
  {
   "title": "Load CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Firmware version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrFirmwareVersion{instance='$instance'}",
     "legendFormat": "{{mtxrFirmwareVersion}}"
    }
   ]
  },
  {
   "title": "CPU Mhz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorFrequency{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "mtxrHlVoltage{instance='$instance'}/10",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "System identity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysIdentity{instance='$instance'}",
     "legendFormat": "{{sysIdentity}}"
    }
   ]
  },
  {
   "title": "Active Fan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrHlActiveFan{instance='$instance'}",
     "legendFormat": "{{mtxrHlActiveFan}}"
    }
   ]
  },
  {
   "title": "License level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrLicLevel{instance='$instance'}",
     "legendFormat": "Lic"
    },
    {
     "expr": "mtxrLicUpgradableTo{instance='$instance'}",
     "legendFormat": "Lic Upgradable To"
    }
   ]
  },
  {
   "title": "Board Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrBoardName{instance='$instance'}",
     "legendFormat": "{{mtxrBoardName}}"
    }
   ]
  },
  {
   "title": "Load system disk",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})"
    }
   ]
  },
  {
   "title": "Load RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})"
    }
   ]
  },
  {
   "title": "System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}",
     "legendFormat": "Load CPU"
    },
    {
     "expr": "mtxrHlTemperature{instance='$instance'}/10",
     "legendFormat": "CPU Temp"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})",
     "legendFormat": "System disk"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "graph",
   "description": "Maximum Transmission Unit",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "MTU", "label": "Maximum Transmission Unit" }
   ],
   "targets": [
    { "expr": "ifMtu{instance='$instance'}", "legendFormat": "{{ifName}}" }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrSerialNumber{instance='$instance'}",
     "legendFormat": "{{mtxrSerialNumber}}"
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrDHCPLeaseCount{instance='$instance'}",
     "legendFormat": "dhcp leases"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$instance'}"
    },
    {
     "expr": "ifOperStatus{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance='$instance'}"
    },
    { "expr": "ifSpeed{instance='$instance'}" },
    {
     "expr": "mtxrInterfaceStatsLinkDowns{instance='$instance'}"
    }
   ]
  },
  {
   "title": "POE Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEStatus{instance='$instance'}"
    }
   ]
  },
  {
   "title": "POE Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEVoltage{instance='$instance'}",
     "legendFormat": "POE Voltage"
    }
   ]
  },
  {
   "title": "POE Current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOECurrent{instance='$instance'}",
     "legendFormat": "POE Current"
    }
   ]
  },
  {
   "title": "POE Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEPower{instance='$instance'}",
     "legendFormat": "POE Power"
    }
   ]
  },
  {
   "title": "Wi-Fi Overall Tx CCQ & Noise",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(mtxrWlApOverallTxCCQ{instance='$instance'}*on(mtxrWlApIndex)group_left(mtxrWlApSsid)mtxrWlApSsid{instance='$instance'})",
     "legendFormat": "TX CCQ - {{mtxrWlApSsid}}"
    },
    {
     "expr": "(mtxrWlApNoiseFloor{instance='$instance'}*on(mtxrWlApIndex)group_left(mtxrWlApSsid)mtxrWlApSsid{instance='$instance'})",
     "legendFormat": "Noise - {{mtxrWlApSsid}}"
    }
   ]
  },
  {
   "title": "Wi-Fi Client count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(mtxrWlApAuthClientCount{instance='$instance'}*on(mtxrWlApIndex)group_left(mtxrWlApSsid)mtxrWlApSsid{instance='$instance'})",
     "legendFormat": "{{mtxrWlApSsid}}"
    },
    {
     "expr": "mtxrDHCPLeaseCount{instance='$instance'}",
     "legendFormat": "DHCP Leases"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Showing values > 0",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "All Simple Queue",
   "type": "graph",
   "description": "Showing values > 0",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(mtxrQueueSimpleBytesIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})*8 ",
     "legendFormat": "In - {{mtxrQueueSimpleName}}"
    },
    {
     "expr": "(irate(mtxrQueueSimpleBytesOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})*8",
     "legendFormat": "Out - {{mtxrQueueSimpleName}}"
    },
    {
     "expr": "(mtxrQueueSimplePCQQueuesIn{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})",
     "legendFormat": "PCQ In - {{mtxrQueueSimpleName}}"
    },
    {
     "expr": "(mtxrQueueSimplePCQQueuesOut{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})",
     "legendFormat": "PCQ Out - {{mtxrQueueSimpleName}}"
    }
   ]
  },
  {
   "title": "All Tree Queue",
   "type": "graph",
   "description": "Showing values > 0",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})*8",
     "legendFormat": "Bytes - {{mtxrQueueTreeName}}"
    },
    {
     "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
     "legendFormat": "PCQ - {{mtxrQueueTreeName}}"
    },
    {
     "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
     "legendFormat": "Dropped - {{mtxrQueueTreeName}}"
    },
    {
     "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
     "legendFormat": "Packets - {{mtxrQueueTreeName}}"
    }
   ]
  },
  {
   "title": "Simple Queue (In/Out/Dropped/PCQ)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue $queuesimple_name",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "repeat": "queuesimple_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})*8",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})*8",
       "legendFormat": "Out"
      },
      {
       "expr": "(irate(mtxrQueueSimpleDroppedIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})",
       "legendFormat": "Dropped In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleDroppedOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})",
       "legendFormat": "Dropped Out "
      },
      {
       "expr": "(mtxrQueueSimplePCQQueuesIn{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})",
       "legendFormat": "PCQ-In"
      },
      {
       "expr": "(mtxrQueueSimplePCQQueuesOut{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})",
       "legendFormat": "PCQ-Out"
      }
     ]
    },
    {
     "title": "Queue $queuesimple_name",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})*8",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})*8",
       "legendFormat": "Out"
      },
      {
       "expr": "(irate(mtxrQueueSimpleDroppedIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})",
       "legendFormat": "Dropped In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleDroppedOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})",
       "legendFormat": "Dropped Out "
      },
      {
       "expr": "(mtxrQueueSimplePCQQueuesIn{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})",
       "legendFormat": "PCQ-In"
      },
      {
       "expr": "(mtxrQueueSimplePCQQueuesOut{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})",
       "legendFormat": "PCQ-Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Tree Queue (Bytes/PCQ/Dropped/Packets)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tree Queue $queuetree_name / $queuetree_parent / $queuetree_flow",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "repeat": "queuetree_name",
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})*8",
       "legendFormat": "Bytes"
      },
      {
       "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "PCQ"
      },
      {
       "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Dropped"
      },
      {
       "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Packets"
      }
     ]
    },
    {
     "title": "Tree Queue $queuetree_name / $queuetree_parent / $queuetree_flow",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})*8",
       "legendFormat": "Bytes"
      },
      {
       "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "PCQ"
      },
      {
       "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Dropped"
      },
      {
       "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Packets"
      }
     ]
    },
    {
     "title": "Tree Queue $queuetree_name / $queuetree_parent / $queuetree_flow",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})*8",
       "legendFormat": "Bytes"
      },
      {
       "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "PCQ"
      },
      {
       "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Dropped"
      },
      {
       "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Packets"
      }
     ]
    },
    {
     "title": "Tree Queue $queuetree_name / $queuetree_parent / $queuetree_flow",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})*8",
       "legendFormat": "Bytes"
      },
      {
       "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "PCQ"
      },
      {
       "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Dropped"
      },
      {
       "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
       "legendFormat": "Packets"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "repeat": "Interface",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Traffic \"$Interface\"",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "*cast/Dascard/Errors/Unknown Protos/Queue length",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "repeat": "Interface",
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    },
    {
     "title": "Interface \"$Interface\"",
     "type": "graph",
     "description": "Showing values > 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Multicast"
      },
      {
       "expr": "irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Multicast"
      },
      {
       "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Broadcast"
      },
      {
       "expr": "irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Broadcast"
      },
      {
       "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unicast"
      },
      {
       "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Unicast"
      },
      {
       "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Discard"
      },
      {
       "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Discard"
      },
      {
       "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Errors"
      },
      {
       "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out Errors"
      },
      {
       "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "In Unknown Protos"
      },
      {
       "expr": "irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
       "legendFormat": "Out queue length"
      }
     ]
    }
   ]
  }
 ]
}